version: 2.1


jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: pip install fastapi uvicorn
      - run:
          name: Smoke Test
          command: |
            python -c "import fastapi; print('FastAPI OK')"

workflows:
  version: 2
  basic:
    jobs:
      - test

