version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Set up Python + Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r mood-tracker/server/requirements.txt
            pip install pytest httpx

      - run:
          name: Run Tests with PYTHONPATH fix
          command: |
            . venv/bin/activate
            PYTHONPATH=./mood-tracker pytest mood-tracker/server/tests/

workflows:
  version: 2
  test-workflow:
    jobs:
      - test

